export const UPDATE_LANGUAGE = "UPDATE_LANGUAGE"

export const UPDATE_THEME = "UPDATE_THEME"

export const UPDATE_SLOGAN = "UPDATE_SLOGAN"

export const UPDATE_INTERVAL = "UPDATE_INTERVAL"

export const UPDATE_FONT_SIZE = "UPDATE_FONT_SIZE"

export const UPDATE_FONT_ALIGN = "UPDATE_FONT_ALIGN"